version: '3'

services:
  manfred-job-fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manfred-fetcher-instance
    restart: unless-stopped
    ports:
      - "8080:5000"
    volumes:
      - ./data:/app/data
      - ./requirements.txt:/app/requirements.txt
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
      
  sqlite-web:
    image: coleifer/sqlite-web
    container_name: manfred-db-admin
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=history.db
    depends_on:
      - manfred-job-fetcher