version: '3'

services:
  manfred-job-fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manfred-fetcher-instance
    restart: unless-stopped
    ports:
      - "8080:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s